// <auto-generated />
namespace Blue_Badge_Project.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class endpoints_1318 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(endpoints_1318));
        
        string IMigrationMetadata.Id
        {
            get { return "202103091603530_endpoints_13/18"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
