// <auto-generated />
namespace Blue_Badge_Project.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class initMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202102190009556_init Migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
